src/app/__init__.py
"""Init the applicaiton."""

from flask import Flask, render_template, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from flask_talisman import Talisman
from . import csp
from os import environ

limiter = Limiter(
    key_func=get_remote_address, default_limits=["2 per second", "1000 per day"]
)


@limiter.request_filter
def ip_whitelist():
    """Add some exemptions to the limiter."""
    return request.remote_addr in ("127.0.0.1", "localhost")


def create_app():
    """App factory."""
    app = Flask(__name__)
    talisman = Talisman(
        app,
        content_security_policy=csp.csp,
        content_security_policy_nonce_in=["script-src"],
        force_https=not environ.get("FLASK_ENV") == "development",
    )

    from . import config, routes

    limiter.init_app(app)
    app.register_blueprint(routes.bp)

    @app.context_processor
    def inject_vars():
        """Inject arbitrary data into all templates."""
        return dict(
            all_rules=config.VALID_RULES,
            all_dialects=list(config.VALID_DIALECTS.values()),
            sqlfluff_version=config.SQLFLUFF_VERSION,
        )

    return app

src/app/routes.py
import base64
import gzip

from flask import Blueprint, redirect, render_template, request, url_for
from sqlfluff.api import fix, lint
from .config import VALID_DIALECTS

bp = Blueprint("routes", __name__)


def sql_encode(data: str) -> str:
    """Gzip and base-64 encode a string."""
    return base64.urlsafe_b64encode(gzip.compress(data.encode())).decode()


def sql_decode(data: str) -> str:
    """Gzip and base-64 decode a string."""
    return gzip.decompress(base64.urlsafe_b64decode(data.encode())).decode()


@bp.route("/", methods=["GET", "POST"])
def home():
    """Render the main page."""
    if request.method == "GET":
        return render_template("index.html", result=False)

    # if there is post data, we have the form and need to encode the SQL
    # to pass to the results route.
    #
    # this encoding dance is to protect against the possibility of getting a very
    # long SQL string that breaks something in HTTP get.
    sql = request.form["sql"]
    dialect = request.form["dialect"]
    return redirect(
        url_for("routes.fluff_results", sql=sql_encode(sql), dialect=dialect)
    )


@bp.route("/fluffed")
def fluff_results():
    """Serve the results page."""
    # we get carriage returns from the form somehow. so split on them and join via
    # regular newline. add a newline to avoid the annoying newline-at-end-of-file error.
    sql = sql_decode(request.args["sql"]).strip()
    sql = "\n".join(sql.splitlines()) + "\n"

    # dialect must be a dialect label for `load_raw_dialect`. VALID_DIALECTS is a
    # dictionary of dialect labels to dialect names. If we have a name, we need to
    # get the label.
    #
    # However, the frontend logic runs on dialect names, so we need to convert the
    # label back to a name for the frontend.
    dialect = request.args["dialect"]
    if dialect in VALID_DIALECTS.values():
        dialect_name = dialect
        dialect_label = next(
            label for label, name in VALID_DIALECTS.items() if name == dialect
        )
    else:
        dialect_label = dialect
        dialect_name = VALID_DIALECTS[dialect]

    try:
        linted = lint(sql, dialect=dialect_label)
        fixed_sql = fix(sql, dialect=dialect_label)
    except RuntimeError as e:
        linted = [
            {
                "start_line_no": 1,
                "start_line_pos": 1,
                "code": "RuntimeError",
                "description": str(e),
            }
        ]
        fixed_sql = sql
    return render_template(
        "index.html",
        results=True,
        sql=sql,
        dialect=dialect_name,
        lint_errors=linted,
        fixed_sql=fixed_sql,
    )

src/app/templates/base.html
<!doctype html>

<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous" nonce="{{ csp_nonce() }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous" nonce="{{ csp_nonce() }}"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous" nonce="{{ csp_nonce() }}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous" nonce="{{ csp_nonce() }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ace.js" type="text/javascript" charset="utf-8" nonce="{{ csp_nonce() }}"></script>
</head>

<body>

    <!-- A two column layout -->
    <div class="container">
        <h1>&#127881 SQLFluff Online &#127881</h1>

        <p>
            <a href='https://github.com/sqlfluff/sqlfluff'>SQLFluff</a> is a SQL
            formatter that is implemented in Python. You can use this app to format
            one-off, adhoc sql that might not be worth saving to a file. Or you can use
            it to see what SQLFluff thinks of your queries. It's up to you!
        </p>

        <p>
            You can check out the source code for this application on GitHub
            (<a href='https://github.com/sqlfluff/sqlfluff-online'>click</a>).
        </p>

        <p>
            Paste your SQL and select your dialect. Hit that button and find your fixed
            SQL with the associated linter errors. Enjoy, friends &#127773.
        </p>

        <hr>

        <div class="row">
            <!-- user input -->
            <div class="col-sm">
                {% block left %}{% endblock %}
            </div>

            <div class="col-sm">
                {% block right %}{% endblock %}
            </div>
        </div>

        <hr>

        <button class="btn btn btn-outline-dark btn-block" type="button" data-toggle="collapse" data-target="#more_info"
            aria-expanded="false" aria-controls="collapseExample">
            Click me for more info on this app
        </button>

        <hr>

        <div class="collapse" id=more_info>
            <p>
                SQLFluff is maintained by a group of <s>talented</s> attractive and
                selfless people who are all driven by a common disdain for poorly
                formatted SQL. If you like fluff's treatment of your queries, feel
                encouraged to check out our group on
                <a href='https://github.com/sqlfluff'>GitHub</a>!
            </p>
            <p>
                This app runs on SQLFluff version {{sqlfluff_version}}, and applies all
                rules in that version. Here is a list of them:
            </p>

            <table class="table table-sm">
                <thead>
                    <tr>
                        <th scope="col">Rule</th>
                        <th scope="col">Description</th>
                    </tr>
                </thead>
                <tbody>

                    {% for code, description in all_rules.items() %}
                    <tr>
                        <th scope="row">{{code}}</th>
                        <td>{{description}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <style>
        body {
            margin: 2em;
            max-width: 1500px;
        }

        #counter-container {
            margin-top: .50rem;
        }

        #counter {
            padding: .25rem .75rem;
        }

    </style>
    {% block scripts %}{% endblock %}
</body>

src/app/templates/index.html
{% extends 'base.html' %}
{% block left %}
<h2>Your Terrible SQL</h2>
<form action='{{url_for("routes.home")}}' method="post">
    <div class="form-group">
        <textarea class="form-control text-monospace" name='sql' data-editor="sql" , id="user_sql"
            rows="20">{{sql}}</textarea>
        <div id="counter-container">
            <small id="counter"></small>
        </div>

    </div>

    <div class="form-group">
        <label for="sql_dialect">Dialect</label>
        <select class="form-control" id="sql_dialect" name='dialect' required>
            {% for d in all_dialects %}
            <option value='{{d}}' {% if dialect and d==dialect %} selected=selected {% endif %}>
                {{d}}
            </option>
            {% endfor %}
        </select>

        <label for="sqlfluff_config">Config</label>
        <textarea class="form-control text-monospace" name='sqlfluff_config' id="sqlfluff_config"
                  rows="8">{{sqlfluff_config}}</textarea>
    </div>

    <button type="submit" class="btn btn-primary mb-2 btn-block" id="submitButton">Help me.</button>
</form>
{% endblock %}


{% block right %}
{% if results %}
<h2>SQLFluff's Fixed SQL</h2>
<textarea id=fixedSQL class="form-control text-monospace" rows="20" readonly>{{fixed_sql}}</textarea>

<hr>

{% if lint_errors %}
<div class="alert alert-danger" role="alert">
    Hi! I found some errors for you to look at
</div>

<table id="table_of_errors" class="table table-hover table-sm">
    <thead>
        <tr>
            <th scope="col">Code</th>
            <th scope="col">Line / Position</th>
            <th scope="col">Description</th>
        </tr>
    </thead>
    <tbody>

        {% for violation in lint_errors %}
        <tr>
            <th scope="row">{{violation['code']}}</th>
            <td>{{violation['start_line_no']}} / {{violation['start_line_pos']}}</td>
            <td><pre>{{violation['description'].replace('\\n','\n')}}</pre></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<div class="alert alert-success" role="alert">
    No problems! Nice job friend.
</div>

{% endif %}
{% endif %}
{% endblock %}


{% block scripts %}
<script nonce="{{ csp_nonce() }}">
    // hook up ACE editor to all textareas with data-editor attribute
    $(function () {
        $('textarea[data-editor]').each(function () {
            var textarea = $(this);
            var mode = textarea.data('editor');
            var editDiv = $(
                '<div>',
                {
                    position: 'absolute',
                    width: textarea.width(),
                    height: textarea.height(),
                    'class': textarea.attr('class')
                }
            ).insertBefore(textarea);
            textarea.css('display', 'none');

            var editor = ace.edit(editDiv[0]);
            editor.renderer.setShowGutter(true);
            editor.getSession().setValue(textarea.val());
            editor.getSession().setMode("ace/mode/" + mode);
            editor.setTheme("ace/theme/chrome");

            var maxLength = 3000;

            // update character counter on keyup
            editor.textInput.getElement().onkeyup = function () {
                var sql = editor.session.getValue()
                var remaining = maxLength - sql.length
                var txt = `${remaining} characters remaining.`
                document.getElementById('counter').textContent = txt

                if (remaining < 0) {
                    document.getElementById("submitButton").disabled = true
                    document.getElementById('counter').className = 'alert alert-warning'
                } else {
                    document.getElementById("submitButton").disabled = false
                    document.getElementById('counter').className = ''
                }
            }

            // disable insert if limit is reached
            var doc = editor.session.doc
            doc.applyAnyDelta = doc.applyAnyDelta || doc.applyDelta
            doc.applyDelta = function (delta) {
                if (delta.action == "insert" && this.$maxLength && this.getValue().length >= this.$maxLength) {
                    return false;
                }
                return this.applyAnyDelta(delta);
            }
            doc.$maxLength = maxLength

            // copy back to textarea on form submit
            textarea.closest('form').submit(function () {
                textarea.val(editor.getSession().getValue());
            })

        });
    });

    // Listen out for Command + Enter to submit form
    window.addEventListener('keydown', function(e) {
        if(e.keyCode == 13 && e.metaKey) {
            document.getElementById('submitButton').click();
        }
    });

</script>
{% endblock %}